services:
  Labo6-WS:
    container_name: wsl6
    image: node:latest
    networks:
      - labo6
      - web
    restart: always
    ports:
      - "3333:3333"
    volumes:
      - ./WebSocket:/app
    working_dir: /app
    command: [ "sh", "-c", "npm i && node index.js" ]
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '200M'
        reservations:
          cpus: '0.05'
          memory: '100M'
  Labo6-API:
    container_name: apil6
    image: node:latest
    networks:
      - labo6
      - web
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./Api:/app
    working_dir: /app
    command: [ "sh", "-c", "npm i && node index.js" ]
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '200M'
        reservations:
          cpus: '0.05'
          memory: '100M'

  mongodb-L6:
    container_name: mongodbl6
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    networks:
      - web
    volumes:
      - ./mongodb_data:/var/lib/mongodb
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '200M'
        reservations:
          cpus: '0.05'
          memory: '100M'

networks:
  labo6:
    internal: true
  web:
    external: true

volumes:
  mongodb_data:
