version: '2.27'
services:
  Labo6-API:
    container_name: apil6
    image: node:latest
    networks:
      - labo6
      - webservices
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    working_dir: /app
    command: [ "sh", "-c", "npm i && node index.js" ]

  mongodb:
    container_name: mongodb
    image: mongo:latest
    networks:
      - labo6
    volumes:
      - ./mongodb_data:/data/db

networks:
  labo6:
    internal: true
  webservices:
    external: true

volumes:
  mongodb_data:
