services:
  Labo6-WS:
      container_name: wsl6
      image: node:latest
      networks:
        - labo6
        - webservices
      restart: always
      ports:
        - "3333:3333"
      volumes:
        - ./WebSocket:/app
      working_dir: /app
      command: [ "sh", "-c", "npm i && node index.js" ]
  Labo6-API:
    container_name: apil6
    image: node:latest
    networks:
      - labo6
      - webservices
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./Api:/app
    working_dir: /app
    command: [ "sh", "-c", "npm i && node index.js" ]

  mongodb-L6:
    container_name: mongodbl6
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    networks:
      - webservices
    volumes:
      - ./mongodb_data:/var/lib/mongodb

networks:
  labo6:
    internal: true
  webservices:
    external: true

volumes:
  mongodb_data:
