services:
  Labo6-WS:
    container_name: wsl6
    image: node:latest
    networks:
      - labo6
      - web
    restart: always
    ports:
      - "3333:3333"
    volumes:
      - ./WebSocket:/app
    working_dir: /app
    command: [ "sh", "-c", "node index.js" ]
    mem_limit: 200m
    mem_reservation: 100m
    cpus: '0.1'
  Labo6-API:
    container_name: apil6
    image: node:latest
    networks:
      - labo6
      - web
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./Api:/app
    working_dir: /app
    command: [ "sh", "-c", "node index.js" ]
    mem_limit: 200m
    mem_reservation: 100m
    cpus: '0.1'

  mongodb-L6:
    container_name: mongodbl6
    image: mongo:latest
    restart: always
    networks:
      - labo6
    volumes:
      - ./mongodb_data:/var/lib/mongodb
    mem_limit: 200m
    mem_reservation: 100m
    cpus: '0.1'

networks:
  labo6:
    internal: true
  web:
    external: true

volumes:
  mongodb_data:
